### ISSUE TITLE
run ts-server without config file failure

### ISSUE THREAD

**Issue by xiangyu5632** [openGemini/openGemini#596]
### Describe the bug（Bug 描述）

Version: openGemini v1.2.0
OS: linux amd64

```
root@ds-opengemini:~/download/openGemini-1.2.0# ./ts-server

 _________   ______    ______   ________  _______  ____   ____  ________  _______     
|  _   _  |.' ____ \ .' ____ \ |_   __  ||_   __ \|_  _| |_  _||_   __  ||_   __ \    
|_/ | | \_|| (___ \_|| (___ \_|  | |_ \_|  | |__) | \ \   / /    | |_ \_|  | |__) |   
    | |     _.____''.  _.____''.   |  _| _   |  _/   \ \ / /     |  _| _   |  __ /
   _| |_   | \____) || \____) | _| |__/ | _| |  \ \_  \ ' /     _| |__/ | _| |  \ \_
  |_____|   \______.' \______.'|________||____| |___|  \_/     |________||____| |___|

2024-05-14 15:13:46.522701589 +0800 CST m=+0.034830744 TSMeta starting
panic: cannot apply command: 3936

goroutine 37 [running]:
github.com/openGemini/openGemini/app/ts-meta/meta.(*storeFSM).executeCmd(0xc000099080?, {0xc0001499c8, {}, {0xc0001b6750}, {0x0, 0x0, 0x0}, 0x0})
	/home/runner/work/openGemini/openGemini/app/ts-meta/meta/store_fsm.go:393 +0x133
github.com/openGemini/openGemini/app/ts-meta/meta.(*storeFSM).ApplyBatch(0xc000260540, {0xc000102ea0, 0x34, 0xcd795cc2245b0?})
	/home/runner/work/openGemini/openGemini/app/ts-meta/meta/store_fsm.go:57 +0x2a6
github.com/hashicorp/raft.(*Raft).runFSM.func2({0xc000172c00, 0x34, 0xc000260540?})
	/home/runner/go/pkg/mod/github.com/hashicorp/raft@v1.3.1/fsm.go:141 +0x1d6
github.com/hashicorp/raft.(*Raft).runFSM(0xc0001a8a00)
	/home/runner/go/pkg/mod/github.com/hashicorp/raft@v1.3.1/fsm.go:216 +0x315
github.com/hashicorp/raft.(*raftState).goFunc.func1()
	/home/runner/go/pkg/mod/github.com/hashicorp/raft@v1.3.1/state.go:146 +0x53
created by github.com/hashicorp/raft.(*raftState).goFunc in goroutine 1
	/home/runner/go/pkg/mod/github.com/hashicorp/raft@v1.3.1/state.go:144 +0x79
```

**Comment by gueFDF** [comment]
Can you assign it to me please? I want to try fix it.

**Comment by gueFDF** [comment]
This doesn't seem to be a problem without a config file.
![1234](https://github.com/openGemini/openGemini/assets/92534811/530b4c84-4c91-43c5-9abb-72d943cb9a74)

Panic occurs in the following code
```go
func (fsm *storeFSM) executeCmd(cmd proto2.Command) interface{} {
	if handler, ok := applyFunc[cmd.GetType()]; ok {
		return handler(fsm, &cmd)
	}
	panic(fmt.Errorf("cannot apply command: %x", cmd.GetType()))
}
```
通过打日志发现,这块好像是因为并没有实现`96:  "CreateSqlNodeCommand"导致的,`

**Comment by xiangyu5632** [comment]
@gueFDF 
dose the cmd Type “3936” mean SqlNodeCommand？

**Comment by gueFDF** [comment]
This is a very strange phenomenon, when added a printed message
```go
func (fsm *storeFSM) executeCmd(cmd proto2.Command) interface{} {
	if handler, ok := applyFunc[cmd.GetType()]; ok {
		return handler(fsm, &cmd)
	}
	fmt.Printf("cannot apply command: %d\n", cmd.GetType())
	panic(fmt.Errorf("cannot apply command: %x", cmd.GetType()))
}
```
Start output
![image](https://github.com/openGemini/openGemini/assets/92534811/035be37d-9440-4413-8916-675890089d7d)

3936 became 96

**Comment by gueFDF** [comment]
I see. The odd number `3936 `above is due to the `String ()` method defined in the PB file for the` Commond _type`. If want to print out the corresponding Commond name, should use `%v`

**Comment by xiangyu5632** [comment]
> I see. The odd number `3936 `above is due to the `String ()` method defined in the PB file for the` Commond _type`. If want to print out the corresponding Commond name, should use `%v`

yes, make sure what the command is and why not be executed

**Comment by xuthus5** [comment]
It is a good idea to run the ts-server service without a configuration file. Is there any new progress on this issue?
